import os
from datetime import datetime, timezone
from pathlib import Path

from vibe_tool.parser import parse_js_file, parse_python_file, generate_file_description

SOURCE_EXTENSIONS = {".js", ".jsx", ".ts", ".tsx", ".py", ".mjs"}

IGNORE_DIRS = {
    "node_modules", ".git", ".vibe", "__pycache__", ".next", ".expo",
    "dist", "build", ".venv", "venv", "env", ".tox", ".mypy_cache",
    ".pytest_cache", "coverage", ".nyc_output",
}


def scan_project(project_dir: Path) -> list[dict]:
    """Walk the project and parse all source files."""
    results = []

    for root, dirs, files in os.walk(project_dir):
        # Prune ignored directories
        dirs[:] = [d for d in dirs if d not in IGNORE_DIRS and not d.startswith(".")]

        for fname in sorted(files):
            fpath = Path(root) / fname
            ext = fpath.suffix

            if ext not in SOURCE_EXTENSIONS:
                continue

            rel_path = str(fpath.relative_to(project_dir))

            try:
                code = fpath.read_text(errors="replace")
            except OSError:
                continue

            if ext in (".py",):
                parsed = parse_python_file(code, rel_path)
            else:
                parsed = parse_js_file(code, rel_path)

            results.append({
                "path": rel_path,
                "parsed": parsed,
                "description": generate_file_description(parsed),
            })

    return results


def render_index(scanned: list[dict], project_dir: Path) -> str:
    """Render the scanned results into a markdown index."""
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines = [
        "# Codebase Index (auto-generated by vibe index)",
        f"Last updated: {now}",
        "",
    ]

    # File Map
    lines.append("## File Map")
    for entry in scanned:
        lines.append(f"{entry['path']} — {entry['description']}")
    lines.append("")

    # Exports (only files with exports or routes)
    has_exports = [e for e in scanned if e["parsed"]["exports"] or e["parsed"]["routes"] or e["parsed"]["tables"]]
    if has_exports:
        lines.append("## Exports")
        for entry in has_exports:
            lines.append(f"### {entry['path']}")
            for route in entry["parsed"]["routes"]:
                lines.append(f"  {route}")
            for table in entry["parsed"]["tables"]:
                lines.append(f"  {table}")
            for export in entry["parsed"]["exports"]:
                lines.append(f"  {export}")
            lines.append("")

    # Dependencies
    has_deps = [e for e in scanned if e["parsed"]["dependencies"]]
    if has_deps:
        lines.append("## Dependencies")
        for entry in has_deps:
            deps = ", ".join(entry["parsed"]["dependencies"])
            lines.append(f"{entry['path']} → {deps}")
        lines.append("")

    # Patterns section placeholder
    lines.append("## Patterns")
    lines.append("[Run `vibe index --deep` for Claude-generated pattern analysis]")
    lines.append("")

    return "\n".join(lines)
